# Model configuration
model:
  name: "noise_hf/redwoodresearch/math_pwd_lock_deepseek_math7b_on_weak_pythia1b"
  max_tokens: 500
  do_sample: false
  temperature: 0.0000000001
  model_path: "redwoodresearch/math_pwd_lock_deepseek_math7b_on_weak_pythia1b"
  tokenizer_path: "deepseek-ai/deepseek-math-7b-base"  # Separate tokenizer path

# Noise parameters
noise:
  std_values: [0.01]
  percentage: 1.0
  mean: 0.0
  seeds: [2]
  # LoRA configuration
  use_lora: true  # Set to true to use LoRA-based noise generation
  lora_r: 8  # Rank of the LoRA adapter (min 8)
  # Advanced LoRA options
  lora_target_modules: null  # Set to null to target all linear layers, or specify a list of module names


# List of task scripts to run
tasks:
  - "pw_gsm8k.py"

# Task configuration
task:
  name: "pw_gsm8k"
  pw_gsm8k:
    path: "pw_gsm8k.py"
    fewshot: 0
    fewshot_seed: 42
    num_problems: 10
    use_chat_template: false
    add_generation_prompt: false
    use_password: false

# Logging
log_dir: "./logs/math_pwd_lock_deepseek_math7b_on_weak_pythia1b/seed_2_sweep"

# Logging configuration
log:
  format: json  # This will save logs in JSON format