# Model configuration
model:
  name: "noise_hf/redwoodresearch/math_pwd_lock_deepseek_math7b_on_weak_pythia1b"
  max_tokens: 300 
  do_sample: false
  temperature: 0.01
  model_path: "redwoodresearch/math_pwd_lock_deepseek_math7b_on_weak_pythia1b"
  tokenizer_path: "deepseek-ai/deepseek-math-7b-base" # "deepseek-ai/deepseek-math-7b-base"  # Separate tokenizer path # defaults model_path if empty
  max_model_len: 500  # Maximum model context length for vLLM

# Useful Modesl
## abliterated model: "noise_hf/failspy/Meta-Llama-3-8B-Instruct-abliterated-v3"
## redwoodresearch/math_pwd_lock_deepseek_math7b_on_weak_pythia1b
## meta-llama/Llama-3.1-8B-Instruct

# Noise parameters
noise:
  std_values: [0.05, 0.05, 0.05, 0.05] # currently doesn't work with noise values == 0.0
  percentage: 1.0
  mean: 0.0
  seeds: [1,2,3]
  lora_r: 8  # Rank of the LoRA adapter (min 8)
  lora_target_modules: null  #NOT VERIFIED # Set to null to target all linear layers, or specify a list of module names

# List of task scripts to run, only use if you want more than one task, and you ahve to add teh configuration below as well
tasks:
  - "pw_gsm8k.py"

# Logging configuration
log:
  log_dir: "./logs/24-3-25/seed_check"
  format: json  # This will save logs in JSON format


