# Model configuration
model:
  name: "noise_hf/redwoodresearch/math_pwd_lock_deepseek_math7b_on_weak_pythia1b"
  max_tokens: 500
  do_sample: false
  temperature: 0.0000000001

# Noise parameters
noise:
  std_values: [0.0055]
  percentage: 1.0
  mean: 0.0
  seeds: [6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]


# List of task scripts to run
tasks:
  - "pw_gsm8k.py"

# Task configuration
task:
  name: "pw_gsm8k"
  pw_gsm8k:
    path: "pw_gsm8k.py"
    fewshot: 0
    fewshot_seed: 42
    num_problems: 10
    use_chat_template: false
    add_generation_prompt: false
    use_password: false

# Logging
log_dir: "./logs/math_pwd_lock_deepseek_math7b_on_weak_pythia1b/0.0055_std_sweep"

# Logging configuration
log:
  format: json  # This will save logs in JSON format