# Model configuration
model:
  name: "noise_hf/redwoodresearch/math_pwd_lock_deepseek_math7b_on_weak_pythia1b"
  max_tokens: 500
  do_sample: false
  temperature: 0.0000000001

# Noise parameters
noise:
  std_values: [0.0045, 0.004575, 0.00465, 0.004725, 0.0048, 0.004875, 0.00495, 0.005025, 0.0051, 0.005175, 0.00525, 0.005325, 0.0054, 0.005475, 0.00555, 0.005625, 0.0057, 0.005775, 0.00585, 0.005925, 0.006]
  percentage: 1.0
  mean: 0.0
  seeds: [2]


# List of task scripts to run
tasks:
  - "pw_gsm8k.py"

# Task configuration
task:
  name: "pw_gsm8k"
  pw_gsm8k:
    path: "pw_gsm8k.py"
    fewshot: 0
    fewshot_seed: 42
    num_problems: 10
    use_chat_template: false
    add_generation_prompt: false
    use_password: false

# Logging
log_dir: "./logs/math_pwd_lock_deepseek_math7b_on_weak_pythia1b/seed_2_sweep"

# Logging configuration
log:
  format: json  # This will save logs in JSON format