# Model configuration
model:
  name: "noise_hf/meta-llama/Meta-Llama-3.1-8B-Instruct"
  max_tokens: 10
  do_sample: false

# Noise parameters
noise:
  std_values: [0.0, 0.0005, 0.001, 0.0015, 0.002, 0.0025]
  percentage: 1.0
  mean: 0.0
  seeds: [1,2,3,4,5]

# List of task scripts to run
tasks:
  - "gsm8k.py"
  - "gsm8k_sandbag.py"

# Task configuration (used for both tasks)
task:
  name: "gsm8k"
  gsm8k:
    path: "gsm8k.py"
    sandbagging: true
    use_cot: true
    fewshot: 0
    num_problems: 4

  arc_challenge:
    path: "sandbag_arc_challenge.py"
    sandbagging: false

# Logging
log_dir: "./logs/No_CoT_25_01_25_v3"