# Analysis configuration file for noise experiments

# Mandatory: Specify the log directory for analyze_noise.py
log_dir: "logs/22-3-25/test_SEED_sweep_test_2"

# Optional: Specify a custom CSV file for plot_noise.py. If not provided, the default '{log_dir}_results.csv' will be used.
#plot_input: ""

# Optional: Specify a custom CSV file for analyze_scaling.py. If not provided, the default '{log_dir}_results.csv' will be used.
#scaling_input: "" 